### PR TITLE
MIT license.

### PR DESCRIPTION
**Pull request by akoenig**

### CODE REVIEW

**Comment by Croydon** [comment]
Don't forget that all former contributors have to agree on the license.

**Comment by akoenig** [comment]
@webkodierer @wuwi What about your thoughts on using the MIT license for the project? The [API](https://github.com/cahoots-extension/api) and the [api-client](https://github.com/cahoots-extension/api-client) are also under this license :)

**Comment by webkodierer** [comment]
+1 
my favourite license

**Comment by wuwi** [comment]
I'm ok with that +1

**Pull request merged**
